### ISSUE TITLE
Need to be updated to support 5.1 domain management

### ISSUE THREAD

**Issue by atlanical** [liquidregistrar/liquid-blesta#2]
Please see: https://docs.blesta.com/display/dev/Registrar+Modules

**Comment by areaprastian** [comment]
Thanks, the team is currently in the process of updating the module to support Blesta 5.1+ version.
Please wait for the next update.

**Comment by areaprastian** [comment]
Please update the latest module. The latest module (v2.1.0) already supports Blesta 5.1+.
